import numpy as np
import graphinglib as gl
from typing import Literal, Self
from astropy.io import fits
from astropy.constants import c as light_speed
from astropy import units as u
from pandas import read_csv

from src.config import REDSHIFT
from src.tools.miscellaneous import get_pdf_image_as_array
from src.coordinates.fits_coords import FitsCoords


class LOKIModels:
    """
    This class implements a simple container for the models of a LOKI run. It contains relevant attributes such as the
    data, wavelengths, total model, etc. It is typically initialized from the `load` class method, which takes as input
    the filename of the `..._full_model.fits` generated by LOKI.
    """
    def __init__(
        self,
        data: np.ndarray,
        wavelengths: np.ndarray,
        stellar_continuum: np.ndarray,
        emission_extinction: np.ndarray,
        total_model: np.ndarray,
        folder_name: str,
    ) -> None:
        """
        Initializes a `LOKIModels` object with the given attributes.

        Parameters
        ----------
        data : np.ndarray
            The data cube from the LOKI output, in units of erg/s/cm²/sr.
        wavelengths : np.ndarray
            The wavelengths array corresponding to the spectral axis of the data cube, in microns.
        stellar_continuum : np.ndarray
            The stellar continuum model cube from the LOKI output, in units of erg/s/cm²/sr.
        emission_extinction : np.ndarray
            The extinction cube for the emission lines from the LOKI output, in units of dimensionless extinction
            factor.
        total_model : np.ndarray
            The total model cube from the LOKI output, in units of erg/s/cm²/sr.
        folder_name : str
            The name of the folder containing the LOKI output files. This is used to locate the CSV files containing
            the Gaussian parameters for individual spaxels when using the `get_gaussian_params` method.
        """
        self.data = data
        self.wavelengths = wavelengths
        self.stellar_continuum = stellar_continuum
        self.emission_extinction = emission_extinction
        self.total_model = total_model
        self.folder_name = folder_name

    @classmethod
    def load(cls, filename: str) -> Self:
        """
        Loads the models of a LOKI run from a FITS file and constructs a `LOKIModels` object.

        Parameters
        ----------
        filename : str
            The filename to the FITS file containing the LOKI models. This is typically the `..._full_model.fits` file.

        Returns
        -------
        Self
            The newly constructed `LOKIModels` object. Note that the wavelengths are corrected for the redshift of the
            source.
        """
        folder_name = "/".join(filename.split("/")[:-1])

        loki_hdus = fits.open(filename)
        data = loki_hdus[1].data  # units are erg/Hz/cm²/s/sr
        wavelengths = loki_hdus[-1].data[0][0].flatten() / (1 + REDSHIFT)

        # Building the stellar continuum
        stellar_extinction = loki_hdus[4].data
        raw_stellar_continuum = loki_hdus[8].data
        polynomials_multiplicative = loki_hdus[7].data
        raw_stellar_continuum *= polynomials_multiplicative
        stellar_continuum = raw_stellar_continuum * stellar_extinction

        # Building the gas emission lines
        gas_extinction = loki_hdus[5].data
        silicates_extinction = loki_hdus[6].data
        emission_extinction = gas_extinction * silicates_extinction
        gas_lines = np.sum([loki_hdus[i].data for i in range(9, len(loki_hdus)-1)], axis=0) * emission_extinction

        # Convert to erg/s/cm²/sr
        hertz_conversion_factor = light_speed.to("micron/s").value / (wavelengths)
        data *= hertz_conversion_factor[:, None, None]
        stellar_continuum *= hertz_conversion_factor[:, None, None]
        gas_lines *= hertz_conversion_factor[:, None, None]

        total_model = stellar_continuum + gas_lines

        return cls(
            data=data,
            wavelengths=wavelengths,
            stellar_continuum=stellar_continuum,
            emission_extinction=emission_extinction,
            total_model=total_model,
            folder_name=folder_name,
        )

    @classmethod
    def load_from_version(
        cls,
        version: Literal["december lr", "february lr", "february hr", "final"] = "final"
    ) -> Self:
        """
        Constructs a `LOKIModels` object from a specified version of the LOKI models.

        Parameters
        ----------
        version : Literal["december lr", "february lr", "february hr", "final"], default="december lr"
            The version of the LOKI models to load. This allows to use predefined versions of the results without
            having to specify the path toward the FITS file. The versions correspond to the following folders:
            - "december lr": `data/loki/output_NGC4696_G235H_F170LP_full_OQBr_tied`
            - "february lr": `data/loki/output_NGC4696_G235H_F170LP_QOBr_tied_global_m1_lores`
            - "february hr": `data/loki/output_NGC4696_G235H_F170LP_QOBr_tied_global_m1_hires`
            - "final": `data/loki/output_NGC4696_G235H_F170LP_QOBr_tied_global_m1_lores_fewlines_largeFWHM`

        Returns
        -------
        Self
            The newly constructed `LOKIModels` object.
        """
        match version:
            case "december lr":
                path = "full_OQBr_tied/NGC4696_G235H_F170LP_full_OQBr_tied"
            case "february lr":
                path = "QOBr_tied_global_m1_lores/NGC4696_G235H_F170LP_QOBr_tied_global_m1_lores"
            case "february hr":
                path = "QOBr_tied_global_m1_hires/NGC4696_G235H_F170LP_QOBr_tied_global_m1_hires"
            case "final":
                path = "QOBr_tied_global_m1_lores_fewlines_largeFWHM/"\
                     + "NGC4696_G235H_F170LP_QOBr_tied_global_m1_lores_fewlines_largeFWHM"
            case _:
                raise ValueError(f"Invalid results version: {version}")

        prefix = "data/loki/output_NGC4696_G235H_F170LP_"
        suffix = "_full_model.fits"
        return cls.load(f"{prefix}{path}{suffix}")

    @property
    def subtracted_stellar_continuum(self) -> np.ndarray:
        """
        Gives the data cube with the stellar continuum subtracted.

        Returns
        -------
        np.ndarray
            The data cube with the stellar continuum subtracted, in units of erg/s/cm²/sr.
        """
        return self.data - self.stellar_continuum

    def slice_wavelengths(self, lambda_min: float, lambda_max: float) -> Self:
        """
        Slices the `LOKIModels` object to a wavelength range of interest.

        Parameters
        ----------
        lambda_min : float
            The minimum wavelength of the slice, in microns.
        lambda_max : float
            The maximum wavelength of the slice, in microns. This value is not included in the slice (i.e., the slice is
            [lambda_min, lambda_max[).

        Returns
        -------
        Self
            A new `LOKIModels` object containing only the data in the specified wavelength range.
        """
        wavelength_mask = (self.wavelengths >= lambda_min) & (self.wavelengths < lambda_max)
        return LOKIModels(
            data=self.data[wavelength_mask],
            wavelengths=self.wavelengths[wavelength_mask],
            stellar_continuum=self.stellar_continuum[wavelength_mask],
            emission_extinction=self.emission_extinction[wavelength_mask],
            total_model=self.total_model[wavelength_mask],
            folder_name=self.folder_name,
        )

    def get_emission_line_fluxes(
        self,
        spaxel_coordinates: tuple[int, int],
        lines: list[str],
        lambda_0s: list[float],
    ) -> np.ndarray:
        """
        Gives the fluxes of the specified lines at a given spaxel. This method allows to get the contribution of
        individual emission components to the fit when there are multiple components for a single line.

        Parameters
        ----------
        spaxel_coordinates : tuple[int, int]
            The (x, y) coordinates of the spaxel for which to extract the Gaussian parameters. These should correspond
            to the coordinates in LOKI/FITS format (i.e., starting at (1, 1)).
        lines : list[str]
            The list of spectral lines to extract the Gaussian parameters for. These should correspond to the names and
            index of the line in LOKI format (e.g., "HI_Pa_alpha.1" for the first Gaussian component of the Pa alpha
            line).
        lambda_0s : list[float]
            The rest wavelengths of the lines in microns. This is needed to convert the velocity parameters (voff and
            fwhm) to wavelength units so that the output array can be used to plot the Gaussian components in wavelength
            space.

        Returns
        -------
        np.ndarray
            A 2D array of shape (len(lines), len(wavelengths)) containing the flux of each Gaussian component for each
            line at the specified spaxel, in units of erg/s/cm²/sr. The fluxes are extinction-corrected.
        """
        if len(lines) != len(lambda_0s):
            raise ValueError("The number of lines must match the number of rest wavelengths provided.")

        # Open the CSV file as a pandas dataframe
        csv_filename = f"{self.folder_name}/output_tables/" \
                     + f"spaxel_{spaxel_coordinates[0]}_{spaxel_coordinates[1]}.final.csv"
        df = read_csv(csv_filename, delimiter="\t")
        df.columns = df.columns.str.strip()
        df["name"] = df["name"].str.strip()
        df = df.set_index("name")

        light_speed_microns = light_speed.to("micron/s").value
        light_speed_km = light_speed.to("kilometer/s").value

        fluxes = []
        for line, lambda_0 in zip(lines, lambda_0s):
            amp = 10**float(df.loc[f"lines.{line}.amp", "best"])  # erg/Hz/cm²/s/sr
            voff = float(df.loc[f"lines.{line}.voff", "best"])  # km/s
            fwhm = float(df.loc[f"lines.{line}.fwhm", "best"])  # km/s

            lambda_center = lambda_0 * (1 + voff / light_speed_km)  # microns
            sigma_lambda = lambda_0 * (fwhm / light_speed_km) / (2 * np.sqrt(2 * np.log(2)))  # microns

            amp_lambda = (light_speed_microns / lambda_center) * amp  # erg/s/cm²/sr
            gaussian = amp_lambda * np.exp(-0.5 * ((self.wavelengths - lambda_center) / sigma_lambda)**2)
            gaussian *= self.emission_extinction[:, *FitsCoords(*spaxel_coordinates)]

            fluxes.append(gaussian)

        fluxes = np.array(fluxes)
        return fluxes

    def get_fit_figure(self, spaxel_coordinates: tuple[int, int]) -> gl.SmartFigure:
        """
        Gives a figure showing the Loki fit for a given spaxel.

        Parameters
        ----------
        spaxel_coordinates : tuple[int, int]
            The (y, x) coordinates of the spaxel to visualize.

            .. note::
                To be consistent with Loki's output, the user may use the `FitsCoords` class to specify coordinates in
                (x, y) format and starting at (1, 1).

        Returns
        -------
        gl.SmartFigure
            The figure showing the Loki fit for the specified spaxel as well as the data itself.
        """
        # Building the emission line labels and texts
        lines = [2.2235, 2.1218, 2.0338, 1.9576, 1.8920, 1.8358, 1.7880, 1.7480, 1.7147, 2.4756, 2.5001 , 2.52802,
                 2.55985, 2.62688, 2.80251, 3.00387, 1.87561, 2.62587, 2.16612, 1.94509]  # some wavelengths from GEMINI
        names = ["S(0)", "S(1)", "S(2)", "S(3)", "S(4)", "S(5)", "S(6)", "S(7)", "S(8)", "Q(6)", "Q(7)", "Q(8)", "Q(9)",
                "O(2)", "O(3)", "O(4)", r"Pa$\alpha$", r"Br$\beta$", r"Br$\gamma$", r"Br$\delta$"]
        name_texts = [gl.Text(line, 0.5, name, font_size=8) for line, name in zip(lines, names)]
        line_vlines = gl.Vlines(lines, colors="gray", line_styles="dashed", line_widths=1)

        data_curve = gl.Curve(self.wavelengths, self.data[:, *spaxel_coordinates],
                            label="data", color="black")
        model_curve = gl.Curve(self.wavelengths, self.total_model[:, *spaxel_coordinates],
                            label="total model", color="#ff5d00")
        continuum_curve = gl.Curve(self.wavelengths, self.stellar_continuum[:, *spaxel_coordinates],
                                label="stellar continuum only", color="fuchsia")
        error_curve = data_curve - model_curve
        error_curve.label = "data - model"

        fig = gl.SmartFigure(
            3,
            x_label=r"$\lambda_\mathrm{rest}$ [$\mu$m]",
            sub_y_labels=[None, r"$\nu I_\nu$ [erg s$^{-1}$ cm$^{-2}$ sr$^{-1}$]", None],
            elements=[
                name_texts,
                [data_curve, model_curve, continuum_curve, line_vlines],
                [error_curve, line_vlines],
            ],
            x_lim=(self.wavelengths.min(), self.wavelengths.max()),
            size=(14.4, 9),
            reference_labels=False,
            share_x=True,
            height_ratios=(0.2, 3, 1),
            height_padding=0,
            general_legend=True,
            legend_loc=(0.85, 0.8),
        ).set_visual_params(use_latex=True).set_ticks(minor_x_tick_spacing=0.05)
        return fig

    @staticmethod
    def get_grid_pdfs_figure(
        lines: list[str],
        folder_name: str = "output_NGC4696_G235H_F170LP_full_model",
    ) -> gl.SmartFigure:
        """
        Gives a figure containing the Loki PDF plots for the specified lines. The figure has 3 columns representing
        flux, velocity offset, and FWHM. These maps are extracted from the "1.flux", "1.voff" and "1.fwhm" files.

        Parameters
        ----------
        lines : list[str]
            The list of spectral lines to include in the figure. These should correspond to Loki output directories in
            the param_maps/lines folder (e.g., "H210_O2").
        folder_name : str, default="output_NGC4696_G235H_F170LP_full_model"
            The folder inside the data/loki directory containing the Loki output.

        Returns
        -------
        gl.SmartFigure
            The figure containing the Loki PDF plots.
        """
        hms = []
        subtitles = []
        for line in lines:
            # for suffix in ["1.flux", "1.voff", "1.fwhm"]:
            for suffix in ["1.flux", "vpeak", "1.fwhm"]:
                hms.append(gl.Heatmap(
                    get_pdf_image_as_array(f"data/loki/{folder_name}/param_maps/lines/{line}/{line}.{suffix}.pdf"),
                    show_color_bar=False,
                ))
                subtitles.append(f"{line} {suffix.lstrip("1.")}")

        num_rows = len(lines)
        fig = gl.SmartFigure(
            num_rows,
            3,
            elements=hms,
            subtitles=subtitles,
            size=(10, 2.75*num_rows),
            remove_axes=True,
            reference_labels=False,
            aspect_ratio=1,
        )
        return fig

    def get_peak_height(self, wavelength: float, channels_tolerance: int = 10) -> float:
        """
        Gives the height of a peak in the total model at a given wavelength. This is useful for plotting the names of
        the peaks just above them.

        Parameters
        ----------
        wavelength : float
            The wavelength at which to get the peak height, in microns.
        channels_tolerance : int, default=10
            The number of channels around the specified wavelength to consider when looking for the peak. This is needed
            to account for small shifts in the peak position due to the fit.

        Returns
        -------
        float
            The height of the peak in the total model at the specified wavelength, in units of erg/s/cm²/sr.
        """
        wavelength_center_channel = np.argmin(np.abs(self.wavelengths - wavelength))
        lower_bound = max(0, wavelength_center_channel - channels_tolerance)
        upper_bound = min(len(self.wavelengths), wavelength_center_channel + channels_tolerance + 1)
        peak_height = self.total_model[lower_bound:upper_bound, :, :].max()
        return peak_height
